cleanup() {
	rm -rf /tmp/spki

	unset -v SPKI_CONFIG_FILE
	unset -v SPKI_ROOT_DIR
	unset -v SPKI_ROOT_PREFIX
	unset -v SPKI_INTRMDT_PREFIX
	unset -v SPKI_ROOT_CRL_DP
	unset -v SPKI_INTRMDT_CRL_DP
	unset -v SPKI_ROOT_OCSP
	unset -v SPKI_INTRMDT_OCSP
	unset -v SPKI_countryName
	unset -v SPKI_stateOrProvinceName
	unset -v SPKI_localityName
	unset -v SPKI_organizationalUnitName
	unset -v SPKI_organizationName
	unset -v SPKI_emailAddress
}

load_vars() {
	countryName=PL
	stateOrProvinceName=Warsaw
	localityName=Warsaw
	organizationalUnitName=Developers
	organizationName=Company\ Ltd
	emailAddress=mail@company.com

	ROOT_COMMON_NAME="Root CA"
	ROOT_COUNTRY_NAME="$countryName"
	ROOT_PROVINCE_NAME="$stateOrProvinceName"
	ROOT_LOCALITY_NAME="$localityName"
	ROOT_ORGANIZATION_NAME="$organizationName"
	ROOT_ORGANIZATIONAL_UNIT_NAME="$organizationalUnitName"
	ROOT_MAIL="$emailAddress"

	ROOT_OCSP_COMMON_NAME="Root CA OCSP"

	INTERMEDIATE_COMMON_NAME="Intermediate CA"
	INTERMEDIATE_COUNTRY_NAME="$countryName"
	INTERMEDIATE_PROVINCE_NAME="$stateOrProvinceName"
	INTERMEDIATE_LOCALITY_NAME="$localityName"
	INTERMEDIATE_ORGANIZATION_NAME="$organizationName"
	INTERMEDIATE_ORGANIZATIONAL_UNIT_NAME="$organizationalUnitName"
	INTERMEDIATE_MAIL="$emailAddress"

	INTERMEDIATE_OCSP_COMMON_NAME="Intermediate CA OCSP"

	CERT_COMMON_NAME="Test Cert"

	ROOT_PRIVATE_KEY_PASSWORD="123456"
	INTERMEDIATE_PRIVATE_KEY_PASSWORD="123456"
	PRIVATE_KEY_PASSWORD="123456"

	ANYKEY="k"
	YES="y"
}

init_from_input() {
	./spki init <<-EOF
	$ROOT_COUNTRY_NAME
	$ROOT_PROVINCE_NAME
	$ROOT_LOCALITY_NAME
	$ROOT_ORGANIZATION_NAME
	$ROOT_ORGANIZATIONAL_UNIT_NAME
	$ROOT_MAIL
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_COMMON_NAME





	
	$ANYKEY$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_COMMON_NAME
	$INTERMEDIATE_COUNTRY_NAME
	$INTERMEDIATE_PROVINCE_NAME
	$INTERMEDIATE_LOCALITY_NAME
	$INTERMEDIATE_ORGANIZATION_NAME
	$INTERMEDIATE_ORGANIZATIONAL_UNIT_NAME
	$INTERMEDIATE_MAIL
	$YES
	$YES
	$ANYKEY
	EOF
}

init_from_input_crl() {
	command -v http-server
	http-server /tmp/spki &> /dev/null &
	export SPKI_ROOT_CRL_DP="URI:http://localhost:8080/crl/ca.crl.der"
	export SPKI_INTRMDT_CRL_DP="URI:http://localhost:8080/intermediate/crl/intermediate.crl.der"

	./spki init <<-EOF
	$ROOT_COUNTRY_NAME
	$ROOT_PROVINCE_NAME
	$ROOT_LOCALITY_NAME
	$ROOT_ORGANIZATION_NAME
	$ROOT_ORGANIZATIONAL_UNIT_NAME
	$ROOT_MAIL
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_COMMON_NAME





	
	$ANYKEY$ANYKEY$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_COMMON_NAME
	$INTERMEDIATE_COUNTRY_NAME
	$INTERMEDIATE_PROVINCE_NAME
	$INTERMEDIATE_LOCALITY_NAME
	$INTERMEDIATE_ORGANIZATION_NAME
	$INTERMEDIATE_ORGANIZATIONAL_UNIT_NAME
	$INTERMEDIATE_MAIL
	$YES
	$YES
	$ANYKEY$ANYKEY
	EOF
	kill %%
}

init_from_input_ocsp() {
	export SPKI_ROOT_OCSP="URI:http://localhost:12345"
	export SPKI_INTRMDT_OCSP="URI:http://localhost:12346"

	./spki init <<-EOF
	$ROOT_COUNTRY_NAME
	$ROOT_PROVINCE_NAME
	$ROOT_LOCALITY_NAME
	$ROOT_ORGANIZATION_NAME
	$ROOT_ORGANIZATIONAL_UNIT_NAME
	$ROOT_MAIL
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_COMMON_NAME





	
	$ANYKEY$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_COMMON_NAME
	$INTERMEDIATE_COUNTRY_NAME
	$INTERMEDIATE_PROVINCE_NAME
	$INTERMEDIATE_LOCALITY_NAME
	$INTERMEDIATE_ORGANIZATION_NAME
	$INTERMEDIATE_ORGANIZATIONAL_UNIT_NAME
	$INTERMEDIATE_MAIL
	$YES
	$YES
	$ANYKEY$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_OCSP_COMMON_NAME






	$YES
	$YES
	$ANYKEY$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_OCSP_COMMON_NAME






	$YES
	$YES
	$ANYKEY
	EOF
}

init_from_envvars() {
	./spki init <<-EOF
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_PRIVATE_KEY_PASSWORD
	$ROOT_COMMON_NAME





	
	$ANYKEY$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$INTERMEDIATE_COMMON_NAME
	$INTERMEDIATE_COUNTRY_NAME
	$INTERMEDIATE_PROVINCE_NAME
	$INTERMEDIATE_LOCALITY_NAME
	$INTERMEDIATE_ORGANIZATION_NAME
	$INTERMEDIATE_ORGANIZATIONAL_UNIT_NAME
	$INTERMEDIATE_MAIL
	$YES
	$YES
	$ANYKEY
	EOF
}

create() {
	./spki create $@ <<-EOF
	$PRIVATE_KEY_PASSWORD
	$PRIVATE_KEY_PASSWORD
	$CERT_COMMON_NAME






	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$YES
	$YES
	$ANYKEY
	EOF
}

create_csr() {
	INTRMDT_CONF="/tmp/spki/intermediate/openssl.cnf"
	KEY="/tmp/spki/intermediate/private/test.key.pem"
	CSR="/tmp/spki/intermediate/csr/test.csr.pem"
	PASS="123456"
	openssl genrsa -aes256 -out "$KEY" -passout "pass:$PASS" 4096
	openssl req -config "$INTRMDT_CONF" -key "$KEY" -new -sha256 -out "$CSR" -passin "pass:$PASS" <<-EOF
	$CERT_COMMON_NAME






	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$YES
	$YES
	$ANYKEY
	EOF
}

revoke() {
	./spki revoke $1 keyCompromise <<-EOF
	$YES
	$INTERMEDIATE_PRIVATE_KEY_PASSWORD
	$ANYKEY
	EOF
}